main: "cc.dreamcode.sands.SandsPlugin"
version: "1.0-InDEV"
name: "Dream-Sands"
description: "Dream-Sands plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "Keymilo"
api-version: 1.13